### ISSUE TITLE
TypeError: path must be a string

### ISSUE THREAD

**Issue by steelbrain** [AtomLinter/atom-linter#105]
```
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.access (fs.js:192:11)
    at /home/steel/.atom/packages/flow-ide/node_modules/atom-linter/lib/helpers.js:244:10
    at findCachedAsync (/home/steel/.atom/packages/flow-ide/node_modules/atom-linter/lib/helpers.js:243:18)
    at Object.<anonymous> (/home/steel/.atom/packages/flow-ide/lib/index.js:54:36)
    at [object Generator].next (native)
    at step (/home/steel/.atom/packages/flow-ide/lib/index.js:3:273)
    at /home/steel/.atom/packages/flow-ide/lib/index.js:3:443
    at Object.lint (/home/steel/.atom/packages/flow-ide/lib/index.js:3:99)
    at linters.forEach.promises.push.Promise.then._this2.emitter.emit.linter (/home/steel/.atom/packages/linter/lib/linter-registry.js:67:26)
    at /home/steel/.atom/packages/linter/lib/linter-registry.js:66:23
    at Set.forEach (native)
    at LinterRegistry.lint (/home/steel/.atom/packages/linter/lib/linter-registry.js:63:18)
    at /home/steel/.atom/packages/linter/lib/linter.coffee:110:16
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /home/steel/.atom/packages/linter/lib/editor-linter.js:20:20
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1067:27)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1037:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:602:26)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:534:18)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:517:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:648:35)
    at atom-workspace.commandRegistry.add.core:save (/usr/share/atom/resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

Seems like we're caching even the null result of atom-linter::findCachedAsync, we shouldn't cache it when it's null

**Comment by steelbrain** [comment]
Fix is in #106
